fix: install nightly version
10up/wpsnapshots pull request #78
Opened 2020-09-30 06:58 UTC by dinhtungdu

Currently, wpsnapshots can't install WP nightly because nightly version is available as zip file, while we only handle gz file for now. This PR fixes this issue by handling zip file for nightly version.

2020-09-30 11:19 UTC, eugene-manuilov commented on src/classes/Command/Pull.php
> +						'filename' => strpos( $download_url, 'zip' ) ? $snapshot_path . 'wp.zip' :$snapshot_path . 'wp.tar.gz',
```suggestion
						'filename' => $snapshot_path . ( false !== stripos( $download_url, '.zip' ) ? 'wp.zip' : 'wp.tar.gz' ),
```

2020-09-30 11:19 UTC, eugene-manuilov commented on src/classes/Command/Pull.php
> +					if ( strpos( $download_url, 'zip' ) ) {
```suggestion
					if ( false !== stripos( $download_url, '.zip' ) ) {
```

2020-10-03 20:03 UTC, eugene-manuilov commented
Although this PR looks good from the first glance, I think we should try to use `ZipArchive` first if it is available, and only then try using `unzip`.

https://www.php.net/manual/en/ziparchive.extractto.php

2020-10-05 08:28 UTC, eugene-manuilov requested changes
Mostly LGTM, left the final comment.

2020-10-05 08:28 UTC, eugene-manuilov commented on src/classes/Command/Pull.php
> +						$zip = new \ZipArchive;
@dinhtungdu let's make sure ZipArchive class exists before we instantiate a new instance:

```php
if ( class_exists( '\ZipArchive' ) {
    $zip = new \ZipArchive();
    ...
} else {
    exec( 'unzip ...' );
}
```

2020-10-05 11:11 UTC, dinhtungdu commented on src/classes/Command/Pull.php
> +						$zip = new \ZipArchive;
@eugene-manuilov Thanks for the headup, didn't think that ZipArchive can be missing

2020-10-05 11:14 UTC, dinhtungdu commented
@eugene-manuilov I moved the extract commands to a private method for better readability, can you please give this PR another review?

2020-10-06 16:02 UTC, eugene-manuilov approved these changes
Thanks, @dinhtungdu! LGTM.

2020-10-06 19:17 UTC, tlovett1 commented
Is anyone actually requesting to use snapshots with the nightly WP version?

2020-10-07 01:33 UTC, dinhtungdu commented
@tlovett1 Yes, we're planning to run WPAcceptance tests against the `latest` and `nightly` version of WordPress for 10up's open source plugins.

2020-10-07 13:21 UTC, jeffpaul commented
Adding to @dinhtungdu's comment, we're doing this to try and proactively catch any conflicts between our plugins and core development before a core release happens and we have to react after-the-fact and with a negative user experience.

2020-10-19 14:53 UTC, jeffpaul commented
@tlovett1 is there anything else you need to unblock merge on this PR?  We're aiming for a ClassifAI release this week and this WP Snapshots enhancement will help with our WP core+ClassifAI test coverage to give us a higher level of confidence in the release, so would be ideal to get this Snapshots PR resolved early this week... thanks!

2020-12-01 23:49 UTC, tlovett1 commented
@eugene-manuilov how do I test this? I assume a snapshot would have `nightly` as the `wp_version` in `meta.json`? I'm wondering how that works with snapshot pushing because if you were running a nightly version and you pushed a snapshot, wouldn't it store the actual version number in meta e.g. 5.6beta2323 or whatever?

2020-12-02 10:31 UTC, dinhtungdu commented
@tlovett1 @eugene-manuilov  to set nightly version, I create a snapshot locally first, then update the wp version in the meta.json file to nightly. After that I push the snapshot by id to AWS.

2021-01-05 10:32 UTC, eugene-manuilov commented
@dinhtungdu can you update your pull request to make sure that the version for nightly snapshots is set correctly when we run the push command?

2021-01-22 15:48 UTC, tlovett1 commented
Updating meta.json manually to me isn't an acceptable workflow for creating a snapshot. I think this needs to be rethought a bit. Ideally, WP Snapshots would allow you somehow to set the version as `latest` or `nightly`. Maybe this happens in the CLI as a prompt.

2021-01-22 17:12 UTC, dinhtungdu commented
@eugene-manuilov @tlovett1 I'm sorry for the late reply. I will add a flag to push/create command to handle the nightly version.

2021-05-03 19:20 UTC, tlovett1 commented
Can you give me instructions on testing this?

2021-05-04 11:42 UTC, dinhtungdu commented
@tlovett1 I add the verification steps to the PR description.

2021-05-17 16:26 UTC, tlovett1 approved these changes

2021-05-17 16:29 UTC, merged